services:
  mysql:
    container_name: db_mysql
    image: fercdevv/mysql_application:latest
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: pwd123
      MYSQL_DATABASE: demo_db
    
    volumes:
      - db_backup_v:/var/lib/mysql

    networks:
      - db_backup_network
    
    ports:
      - 3307:3306
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
  data-copy:
    image: busybox
    container_name: copy-db
    volumes:
      - db_backup_v:/data_copy
      - ./db-backup_noscript:/backup
    entrypoint: /bin/sh -c "cp -r /data_copy/* /backup/"
    depends_on:
      mysql: 
        condition: service_healthy
  

volumes:
  db_backup_v:

networks:
  db_backup_network:

